/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ActivityIndexImport } from './routes/activity/index'
import { Route as ActivityActivityIdImport } from './routes/activity/$activityId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActivityIndexRoute = ActivityIndexImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRoute,
} as any)

const ActivityActivityIdRoute = ActivityActivityIdImport.update({
  id: '/activity/$activityId',
  path: '/activity/$activityId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/activity/$activityId': {
      id: '/activity/$activityId'
      path: '/activity/$activityId'
      fullPath: '/activity/$activityId'
      preLoaderRoute: typeof ActivityActivityIdImport
      parentRoute: typeof rootRoute
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity/$activityId': typeof ActivityActivityIdRoute
  '/activity': typeof ActivityIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity/$activityId': typeof ActivityActivityIdRoute
  '/activity': typeof ActivityIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/activity/$activityId': typeof ActivityActivityIdRoute
  '/activity/': typeof ActivityIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity/$activityId' | '/activity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity/$activityId' | '/activity'
  id: '__root__' | '/' | '/activity/$activityId' | '/activity/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityActivityIdRoute: typeof ActivityActivityIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityActivityIdRoute: ActivityActivityIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/activity/$activityId",
        "/activity/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/activity/$activityId": {
      "filePath": "activity/$activityId.tsx"
    },
    "/activity/": {
      "filePath": "activity/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
